FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install python-software-properties
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get install nodejs
RUN apt-get install redis-server
RUN apt-get install openjdk-8-jdk
RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
RUN echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee /etc/apt/sources.list.d/neo4j.list
RUN apt-get update
RUN apt-get install neo4j
RUN apt-get install openjdk-8-jre

ENTRYPOINT

EXPOSE 8000
EXPOSE 4000